dist: bionic
language: csharp
solution: IndentityServer4.Contrib.Caching.Distributed.sln
mono: none
dotnet: 2.2.204
env:
  global:
    - RedisCacheOptions__Configuration="127.0.0.1:6379"
    - RedisCacheOptions__InstanceName="IdentityServer.Contrib.Caching.Ci.Redis"
stages:
  - build
  - test
  - publish
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      services: redis-server
      script: ./run-tests.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$NUGET_APIKEY" "$TRAVIS_TAG"

